Metadata:
  'AWS::CloudFormation::Designer':
    9c274ab7-ca52-4db9-926a-e0d275008c53:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 150
      z: 1
      embeds: []
      dependson:
        - 5748485b-9610-4810-a07d-3375cceb9908
        - 31669ef5-f09c-42b9-9ffe-cebfa2020b88
    8d59794e-e355-4437-b199-af4c04f1b8cb:
      size:
        width: 60
        height: 60
      position:
        x: 210
        'y': 270
      z: 1
      embeds: []
    fe9df04c-7d01-4697-b151-4c55de723ece:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    31669ef5-f09c-42b9-9ffe-cebfa2020b88:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - fe9df04c-7d01-4697-b151-4c55de723ece
    fa1a9fcf-9997-4fdb-a607-48c552d126ac:
      source:
        id: 9c274ab7-ca52-4db9-926a-e0d275008c53
      target:
        id: 31669ef5-f09c-42b9-9ffe-cebfa2020b88
      z: 11
AWSTemplateFormatVersion: 2010-09-09
Description: RDS-PROXY
Parameters:
  ProxyName:
    Type: String
    Default: exampleProxy
  DBInstanceIdentifier:
    Type: String
    Default: database-1
  DBSecretsManagerArn:
    Type: String
  DebugLogging:
    Description: >-
      Whether the proxy includes detailed information about SQL statements in
      its logs. This information helps you to debug issues involving SQL
      behavior or the performance and scalability of the proxy connections. The
      debug information includes the text of SQL statements that you submit
      through the proxy. Thus, only enable this setting when needed for
      debugging, and only when you have security measures in place to safeguard
      any sensitive information that appears in the logs.
    Type: String
    Default: false
    AllowedValues:
      - false
      - true
  EngineFamily:
    Description: >-
      The kinds of databases that the proxy can connect to. This value
      determines which database network protocol the proxy recognizes when it
      interprets network traffic to and from the database. The engine family
      applies to MySQL and PostgreSQL for both RDS and Aurora.
    Type: String
    Default: POSTGRESQL
    AllowedValues:
      - MYSQL
      - POSTGRESQL
  RequireTLS:
    Description: >-
      A Boolean parameter that specifies whether Transport Layer Security (TLS)
      encryption is required for connections to the proxy. By enabling this
      setting, you can enforce encrypted TLS connections to the proxy.
    Type: String
    Default: true
    AllowedValues:
      - false
      - true
  VpcSecurityGroupIds:
    Description: One or more VPC security group IDs to associate with the new proxy.
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  SubnetIds:
    Description: List of subnets diveded by comma.
    Type: String
    Default: 'subnet-01b761b31fb498f20,subnet-012b9a958ef0f9949,subnet-05e8e263052025378'
  RDSProxyKmsKeyArn:
    Description: RDS KMS Key ID
    Type: String
Resources:
  DBProxy:
    Type: 'AWS::RDS::DBProxy'
    Properties:
      DebugLogging: !Ref DebugLogging
      DBProxyName: !Ref ProxyName
      EngineFamily: !Ref EngineFamily
      IdleClientTimeout: 120
      RequireTLS: !Ref RequireTLS
      RoleArn:
        'Fn::GetAtt':
          - RootRole
          - Arn
      Auth:
        - AuthScheme: SECRETS
          SecretArn: !Ref DBSecretsManagerArn
          IAMAuth: DISABLED
      VpcSubnetIds:
        'Fn::Split':
          - ','
          - !Ref SubnetIds
      VpcSecurityGroupIds: !Ref VpcSecurityGroupIds
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9c274ab7-ca52-4db9-926a-e0d275008c53
    DependsOn:
      - RootRole
  DBProxyTargetGroup:
    Type: 'AWS::RDS::DBProxyTargetGroup'
    Properties:
      DBProxyName: !Ref DBProxy
      DBInstanceIdentifiers:
        - !Ref DBInstanceIdentifier
      TargetGroupName: default
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 80
        MaxIdleConnectionsPercent: 20
        ConnectionBorrowTimeout: 120
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8d59794e-e355-4437-b199-af4c04f1b8cb
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'rds-proxy-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref SampleManagedPolicy
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 31669ef5-f09c-42b9-9ffe-cebfa2020b88
  SampleManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: GetSecretValue
            Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: !Ref DBSecretsManagerArn
          - Sid: DecryptSecretValue
            Effect: Allow
            Action:
              - 'kms:Decrypt'
            Resource: !Ref RDSProxyKmsKeyArn
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fe9df04c-7d01-4697-b151-4c55de723ece
